services:
  postgres:
    image: 'postgres:latest'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge