// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/gin-gonic/gin"
	"github.com/raychongtk/wallet/datastore"
	"github.com/raychongtk/wallet/repository"
	"github.com/raychongtk/wallet/service"
)

// Injectors from inject_routes.go:

func injectRoutes(ctx context.Context) (*gin.Engine, error) {
	db := datastore.ProvideDBConnection()
	userRepository := repository.ProvideUserRepository(db)
	movementRepository := repository.ProvideMovementRepository(db)
	accountRepository := repository.ProvideAccountRepository(db)
	walletRepository := repository.ProvideWalletRepository(db)
	transactionRepository := repository.ProvideTransactionRepository(db)
	balanceRepository := repository.ProvideBalanceRepository(db)
	paymentHistoryRepository := repository.ProvidePaymentHistoryRepository(db)
	client := datastore.ProvideRedis()
	serviceService, err := service.ProvideService(userRepository, movementRepository, accountRepository, walletRepository, transactionRepository, balanceRepository, paymentHistoryRepository, db, client)
	if err != nil {
		return nil, err
	}
	engine := service.ProvideRoutes(serviceService)
	return engine, nil
}
