// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/gin-gonic/gin"
	"github.com/raychongtk/wallet/datastore"
	"github.com/raychongtk/wallet/repository"
	"github.com/raychongtk/wallet/route"
	"github.com/raychongtk/wallet/service"
)

// Injectors from inject_routes.go:

func injectRoutes(ctx context.Context) (*gin.Engine, error) {
	db := datastore.ProvideDBConnection()
	userRepository := repository.NewRepository(db)
	serviceService, err := service.ProvideService(userRepository)
	if err != nil {
		return nil, err
	}
	engine := route.ProvideRoutes(serviceService)
	return engine, nil
}
